### ISSUE TITLE
Question about starting the app

### ISSUE THREAD

**Issue by IbrahimShehade** [AbdelilahOu/Mahalli-tauri#15]
السلام عليكم 
حابب استعمل هذا البرنامج لكن في errors  عم تطلع مثل 
thread 'main' panicked at src\db.rs:17:43:
called `Result::unwrap()` on an `Err` value: NotPresent
في dependencies مطلوبة لنسوي run لل app ؟

**Comment by AbdelilahOu** [comment]
@IbrahimShehade وعليكم السلام
Line 17 I'm sure its  the database url that is missing, you need a .env file like this :
```
DATABASE_URL='sqlite://mahalli.sqlite?mode=rwc'
TAURI_DEV_WATCHER_IGNORE_FILE=.taurignore
```
Make sure to put it inside the src-tauri folder,
Also check [https://tauri.app/v1/guides/getting-started/prerequisites/](tauri prerequisite) to setup rust and tauri correctly

**Comment by AbdelilahOu** [comment]
Also check the Makefile in the root directory for all the commends that you need to run the app
