### ISSUE TITLE
Delete Seed.rs file

### ISSUE THREAD

**Issue by IbrahimShehade** [AbdelilahOu/Mahalli-tauri#17]
Hello, I tried to delete the seed.rs file but in build the app won't open could you afford some help.

**Comment by AbdelilahOu** [comment]
Yes ofc, after you delete the file go to the lib.rs file inside the migrations folder and delete the line number 6 : `mod m20240216_201704_seed_init_;` and line number 16 : `Box::new(m20240216_201704_seed_init_::Migration),`
