### ISSUE TITLE
error while generating the build file

### ISSUE THREAD

**Issue by vanderleisp** [AbdelilahOu/Mahalli-tauri#19]
interesting project, as I´m learning about local-first, so Tauri could be an option.

could generate the dev file and run in a browser, but then trying to generate the build file now crash like 30 times, and seems all related to the '$route' not existing on Vue ?? below is one of the crashs as example:

src/components/QuoteDelete.vue:52:35 - error TS2339: Property '$route' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { Button: __VLS_WithTemplateSlots<DefineComponent<__VLS_WithDefaults<__VLS_TypePropsToOption<Props>, { as: string; }>, ... 11 more ..., {}>, { ...; }>; UiModalCard: __VLS_WithTemplateSlots<...>; t: ComposerTranslation<...>; deleteTheQuotes: (id: string) =...'.

52           @click="deleteTheQuotes($route.query?.id as string)"

Also any plan to include Android/iOS Tauri on it ?
and move the server to something like Supabase or another backend ?

**Comment by vanderleisp** [comment]
found a workaround for the problem, basically fixing on package.json the vue-router version to 4.4.0 without the ^

now the next problem is that a property used at id.vue doesn´t exist, so seems you´ll need to use another way ?

src/pages/index/orders/[id].vue:22:30 - error TS2339: Property 'id' does not exist on type 'Record<never, never> | { id: string; } | { id: string; } | { id: string; } | { id: string; } | { id: string; }'.
  Property 'id' does not exist on type 'Record<never, never>'.

22 const id = useRoute().params.id;

**Comment by AbdelilahOu** [comment]
I have been using [unplugin-vue-router](https://github.com/posva/unplugin-vue-router) to generate my routes it seems like its having some issues getting the typed routes, I have pushed a change you can pull the new version from main, I also updated the project to bun which is better for performance (if you got any other problems lemme know and if you like the project give it a star thank you)

**Comment by AbdelilahOu** [comment]
for migrating the backend I have already using Golang and Postgres but this is a private repo (sorry) if you are familiar with Rust you can migrate the backend to actix web and I have an example  [project](https://github.com/AbdelilahOu/Rusty-school) built with actix-web and sea-orm you can use the existing services in this project all you have to do is define the routes you need, but mainly I have no plans for this project I have migrated to another private project built using [nuxt](https://trymahalli.com), but I would be glad to help and collaborate

**Comment by vanderleisp** [comment]
thanks.

I downloaded the new code, and it´s running again on dev (had to update cargo as had the 'time' crate with problem because of an API change), and then in the build it crashed again, on same two of the previous problems (the way 'id' property is used seems wrong, but I don´t know how to change the two files - clients and suppliers [id].vue):

vite v5.4.10 building for production...
transforming (2893) node_modules\d3-sankey\node_modules\d3-shape\src\curve\basis.jssrc/pages/index/clients/[id].vue:12:9 - error TS2339: Property 'id' does not exist on type 'Record<never, never> | { id: string; } | { id: string; } | { id: string; } | { id: string; } | { id: string; }'.

12 const { id } = useRoute().params;
           ~~

src/pages/index/suppliers/[id].vue:12:9 - error TS2339: Property 'id' does not exist on type 'Record<never, never> | { id: string; } | { id: string; } | { id: string; } | { id: string; } | { id: string; }'.

12 const { id } = useRoute().params;

**Comment by vanderleisp** [comment]
> for migrating the backend I have already using Golang and Postgres but this is a private repo (sorry) if you are familiar with Rust you can migrate the backend to actix web and I have an example [project](https://github.com/AbdelilahOu/Rusty-school) built with actix-web and sea-orm you can use the existing services in this project all you have to do is define the routes you need, but mainly I have no plans for this project I have migrated to another private project built using [nuxt](https://trymahalli.com), but I would be glad to help and collaborate

My coding expetise is little, just learning how to make an app, initially trying to make a local-first CRM that will have its own DB and then get or update a server file (in some places internet isn´t that good, so then if need an info and can´t access server then you would get stuck driving around to find connection), so I found your solution similar to that, and interesting to what I´m looking, and then seeing if Tauri could be an option to have web/Windows and mobile with same or similar code, as using like React then can´t use same code on mobile and use like React Native, or like Flutter for both ends.

**Comment by AbdelilahOu** [comment]
I see, You could use tauri for both desktop and mobile and you could even turn that code into a webapp it would be much easier if you use supabase or firebase or an external server as long as its not tied up to tauri's rust side like the case of this app
If you need any help you could reach out on twitter feel free

**Comment by AbdelilahOu** [comment]
> never, never> | { id: string; } | { id: string; } | { id: string; } | { id: string; } | { id: string; }'.\n\n12 const { id } = useRoute().params;

So that you can build the app you can that line to  `const { id } = useRoute().params as any;`  so that you can avoid type errors for now, i will fix this issue later

**Comment by AbdelilahOu** [comment]
> thanks.
> 
> I downloaded the new code, and it´s running again on dev (had to update cargo as had the 'time' crate with problem because of an API change), and then in the build it crashed again, on same two of the previous problems (the way 'id' property is used seems wrong, but I don´t know how to change the two files - clients and suppliers [id].vue):
> 
> vite v5.4.10 building for production... transforming (2893) node_modules\d3-sankey\node_modules\d3-shape\src\curve\basis.jssrc/pages/index/clients/[id].vue:12:9 - error TS2339: Property 'id' does not exist on type 'Record<never, never> | { id: string; } | { id: string; } | { id: string; } | { id: string; } | { id: string; }'.
> 
> 12 const { id } = useRoute().params; ~~
> 
> src/pages/index/suppliers/[id].vue:12:9 - error TS2339: Property 'id' does not exist on type 'Record<never, never> | { id: string; } | { id: string; } | { id: string; } | { id: string; } | { id: string; }'.
> 
> 12 const { id } = useRoute().params;

I have fixed the typescript errors you can build the app without any type issues now
